In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [6]:
from sklearn.datasets import load_iris
data=load_iris()
print(data.keys())
print(data.DESCR)
print(data.feature_names)
print(data.target)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= =====

In [8]:
df=pd.DataFrame(data.data,columns=data.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
df["Target"]=data.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
145       2  
146       2  
147       2  
148       2  
149       2

In [13]:
df.sample(6)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
141                6.9               3.1                5.1               2.3   
33                 5.5               4.2                1.4               0.2   
112                6.8               3.0                5.5               2.1   
65                 6.7               3.1                4.4               1.4   
86                 6.7               3.1                4.7               1.5   
30                 4.8               3.1                1.6               0.2   

     Target  
141       2  
33        0  
112       2  
65        1  
86        1  
30        0

In [14]:
df["Target"].unique()

array([0, 1, 2])

In [16]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)
print(x_train.shape,x_test.shape)

(120, 4) (30, 4)


In [19]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=300)  # max_iter =300 beacuse max_iter default value is 100 and at this value it doesn't reach to global minima
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
print(model.predict_proba(x_test))

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2]
[[9.84735704e-01 1.52642738e-02 2.17672162e-08]
 [2.76088230e-01 7.21263668e-01 2.64810188e-03]
 [6.27952136e-03 8.89212804e-01 1.04507675e-01]
 [9.85517658e-01 1.44822783e-02 6.33390208e-08]
 [1.18190271e-06 1.90368194e-02 9.80961999e-01]
 [4.52711988e-03 6.27844237e-01 3.67628643e-01]
 [1.47094626e-04 1.27729789e-01 8.72123117e-01]
 [9.57852179e-01 4.21465940e-02 1.22722845e-06]
 [9.69596751e-01 3.04029399e-02 3.09036489e-07]
 [9.75929700e-06 2.70679642e-02 9.72922277e-01]
 [1.89919308e-02 8.79730522e-01 1.01277547e-01]
 [9.66510553e-01 3.34890045e-02 4.42264014e-07]
 [4.72230250e-06 3.10316994e-02 9.68963578e-01]
 [7.14711237e-03 8.01817456e-01 1.91035431e-01]
 [6.98047472e-03 7.49164755e-01 2.43854770e-01]
 [9.88120231e-01 1.18797023e-02 6.71076071e-08]
 [2.25109780e-02 9.36990773e-01 4.04982495e-02]
 [1.09650313e-02 6.81832127e-01 3.07202842e-01]
 [9.59478287e-01 4.05214104e-02 3.02965746e-07]
 [9.82098324e-01 1.7901628

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

